name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/deploy.yml"

  workflow_dispatch:

  schedule:
    - cron: "7 7 7/14 * *"

permissions:
  contents: read

concurrency:
  group: "deploy"
  cancel-in-progress: false

env:
  default_node_version: "lts/*"
  destination: "./src"

jobs:
  deploy_surge:
    name: Deploy to Surge
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: "surge-cli-action.surge.sh"
      url: "${{ steps.get_url.outputs.url }}"
    steps:
      - uses: actions/checkout@v4

      - uses: uiolee/surge-cli-action@v0.23.1
        with:
          surge-args: "${{ env.destination }} "
          # surge-args: "<project> <domain>"
          surge-token: ${{ secrets.SURGE_TOKEN }}
          surge-email: ${{ secrets.SURGE_EMAIL }} # Just used to mask your email address

      - name: get domain from CNAME
        id: get_url
        run: echo -n "url=$(cat ${{ env.destination }}/CNAME)" >> "$GITHUB_OUTPUT"

      - name: output summary
        run: echo "${{ steps.get_url.outputs.url }}" >> $GITHUB_STEP_SUMMARY
